export const initialState = {
  posts: {
    data: [
      {
        id: '1',
        title: 'Looking for a roommate',
        content: 'Are you looking for a great place to live? We offer you a nice room for rent. Fully equiped! Ready to accommodate',
        date: '10.10.2010',
        updateDate: '11.10.2010',
        mail: 'johndoe@example.com',
        status: 'published',
        image: 'https://i.ibb.co/MRwRfY3/simon-abrams-e-Mnddgd3pj-Q-unsplash.jpg',
        userId: '1',
      },
      {
        id: '2',
        title: 'Keys found',
        content: 'I found some keys on a bus stop Królewska yesterday. Will be happy to give them back to the owner.',
        date: '20.05.2019',
        updateDate: '21.05.2020',
        mail: 'johndoe@example.com',
        status: 'published',
        userId: '1',
      },
      {
        id: '3',
        title: 'Japanese lessons',
        content: 'Professional Japanese teacher will give lessons to all who want to learn that beautiful language.',
        date: '20.01.2020',
        updateDate: '21.02.2020',
        mail: 'karinhoe@example.com',
        status: 'published',
        image: 'https://i.ibb.co/TcFrbw4/freddie-marriage-g-L-7-Nt-Zp-YI-unsplash-1.jpg',
        userId: '2',
      },
      {
        id: '4',
        title: 'Keys found',
        content: 'I found some keys on a bus stop Królewska yesterday. Will be happy to give them back to the owner.',
        date: '20.05.2019',
        updateDate: '21.05.2020',
        mail: 'johndoe@example.com',
        status: 'published',
        userId: '1',
      },
      {
        id: '5',
        title: 'Japanese lessons',
        content: 'Professional Japanese teacher will give lessons to all who want to learn that beautiful language.',
        date: '20.01.2020',
        updateDate: '21.02.2020',
        mail: 'anny@example.com',
        status: 'published',
        image: 'https://i.ibb.co/TcFrbw4/freddie-marriage-g-L-7-Nt-Zp-YI-unsplash-1.jpg',
        userId: '3',
      },
    ],
    loading: {
      active: false,
      error: false,
    },
  },
  users: [
    { id: '1', mail: 'johndoe@example.com' },
    { id: '2', mail: 'karinhoe@example.com' },
    { id: '3', mail: 'anny@example.com' },
  ],
};
